baseurl = "https://www.franciscoandrade.dev" # Hostname (and path) to the root.
title = "Francisco Andrade" # Site title.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

copyright = "Francisco Andrade"

[params] # theme parameters
    author = "Francisco Andrade" # Author's name.
    info = "WEB AND APPS ENGINEER" # Author's job title or info.
    description = "Francisco Andrade's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/avatar.png" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "Enter a text here." # Add footer content
    fixedbarContent = "Do you want to know me more private?→" # Add fixedbar content
    fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    icon = "github"
    weight = 1
    url = "https://github.com/fdfandrade/"
[[params.social]]
    icon = "twitter"
    weight = 2
    url = "https://twitter.com/fdfandrade/"
[[params.social]]
    icon = "linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/fdfandrade/"

# Menu links
#[[menu.main]]
#    name = "Blog"
#    weight = 1
#    url  = "posts"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"